### ISSUE TITLE
B2C UI Feedback

### ISSUE THREAD

**Issue by mariocnovoa** [lana/b2c-mapp-ui#27]
Link to Figma for documentation of changes:
https://www.figma.com/file/7qn2DSkgoUT5i9hIt4FL1C/Storybook?node-id=0%3A1

**Comment by jasonadt** [comment]
@mariocnovoa I've just finished applying all of the feedback you shared with me via the Figma link you've shared above (with the exception of the Icons and the Loading Spinner, which will need to be updated later). Please check our latest Storybook deployed here: https://lana.github.io/b2c-mapp-ui/ and let me know if you have any new feedback.
