### ISSUE TITLE
B2C UI Feedback - V2

### ISSUE THREAD

**Issue by mariocnovoa** [lana/b2c-mapp-ui#31]
I leave here the documented feedback:
https://www.figma.com/file/7qn2DSkgoUT5i9hIt4FL1C/Storybook?node-id=71%3A411

**Comment by jasonadt** [comment]
@mariocnovoa I've finished addressing this feedback: https://lana.github.io/b2c-mapp-ui/

 Please let me know if you have any further change requests.
