### ISSUE TITLE
Screen transitions

### ISSUE THREAD

**Issue by mariocnovoa** [lana/b2c-mapp-ui#88]
Implement the way web screens transition between them from right to left to go forward and from left to right to go back (same as in native)
Ex: in FAQ's when we click on the category it should go forward and backward as follows:

[Screen-transitions.mp4.zip](https://github.com/lana/b2c-mapp-ui/files/5255108/Screen-transitions.mp4.zip)

**Comment by jasonadt** [comment]
@JoseOrtiz please comment and close this issue after you've added transitions to `cl-merino`. Thanks much! 😃

**Comment by jasonadt** [comment]
This has been implemented in `mx-merino`, `cl-merino`, and `b2c-access`. Please let us know if you'd like any further changes or improvements.
