### ISSUE TITLE
Forms 2.0 - Bugs

### ISSUE THREAD

**Issue by mariocnovoa** [lana/b2c-mapp-ui#99]
- [x] Review the alignment of the emoji flag
![image](https://user-images.githubusercontent.com/47601204/94691210-51778400-0331-11eb-9583-f1f9565e1ef3.png)
![Screenshot_20200930-152416](https://user-images.githubusercontent.com/47601204/94691228-589e9200-0331-11eb-8493-30d641af2139.png)
![Screenshot_20200930-152800](https://user-images.githubusercontent.com/47601204/94691441-96031f80-0331-11eb-8f92-7ac8780e772e.png)

- [x] In the X of delete the content when you press it, the blue background that used to appear in the buttons

**Comment by jasonadt** [comment]
Both issues have been fixed. I'm updating `mx-merino` and `b2c-access` to use this latest version now.
